# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER  David Greiner <david@ultitech.de>

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
