# Image created by Oracle
FROM influxdb:latest

# File Author / Maintainer
MAINTAINER  David Greiner <greiner@teco.edu>

# Execute jacitivity2.sql on build
ADD jactivity2.sql /docker-entrypoint-initdb.d/jactivity2.sql
